project_id = "qzbooggfhdeejceiiuuj"

[functions.chat]
verify_jwt = false

[functions.parse-document]
verify_jwt = false

[functions.send-email-gmail]
verify_jwt = false

[functions.notify-ticket]
verify_jwt = false